apiVersion: v2
name: login-test-backend
description: A Helm chart for login_test_backend with MySQL dependency
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mysql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami