apiVersion: apps/v1 
kind: Deployment
metadata:
  name: login_test_backend
spec:
  selector:
    matchLabels:
      app: login_test_backend
  template:
    metadata:
      labels:
        app: login_test_backend
    spec:
      containers:
      - name: login_test_backend
        image: harbor.alfredbrowniii.io/test/login_test_backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: login_test_backend
spec:
  selector:
    app: login_test_backend
  ports:
  - port: 8080
    targetPort: 8080

